"""add email verification token fields

Revision ID: 28f325d8aaf2
Revises: bd480a3ed0d0
Create Date: 2026-02-16 15:28:02.704491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f325d8aaf2'
down_revision = 'bd480a3ed0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uzivatel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_uzivatel_email_verification_token'), ['email_verification_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uzivatel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uzivatel_email_verification_token'))
        batch_op.drop_column('email_verification_expires_at')
        batch_op.drop_column('email_verification_token')

    # ### end Alembic commands ###
