"""remove zastavky

Revision ID: 8a14ba7111c9
Revises: e3fa6dec6a49
Create Date: 2026-02-10 22:00:50.011221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a14ba7111c9'
down_revision = 'e3fa6dec6a49'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if "zastavka" in insp.get_table_names():
        op.drop_table("zastavka")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jizda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'auto', ['auto_id'], ['id'])
        batch_op.alter_column('auto_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('zastavka',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jizda_id', sa.INTEGER(), nullable=False),
    sa.Column('nazev', sa.VARCHAR(length=255), nullable=False),
    sa.Column('poradi', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['jizda_id'], ['jizda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
